/**
 * Device chrome manifest loader — maps device_type strings to frame assets.
 *
 * The manifest is generated by `scripts/prepare-device-chrome.mjs` and placed
 * in `public/device-chrome/manifest.json`. It maps simulator device names
 * (e.g. "iPhone 16 Pro") to their frame asset URL and screen inset percentages.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DeviceChromeSpec {
  /** Chrome family identifier (e.g. "phone11", "tablet5") */
  chromeId: string;
  /** URL to the frame asset (SVG or WebP) in public/ */
  asset: string;
  /** CSS aspect-ratio value for the full device frame (e.g. "436 / 908") */
  aspectRatio: string;
  /** Screen inset percentages — top/bottom are % of height, left/right are % of width */
  screen: {
    top: number;
    left: number;
    right: number;
    bottom: number;
  };
  /** URL to the framebuffer mask SVG (for screen corner clip-path), or null */
  mask: string | null;
}

// ---------------------------------------------------------------------------
// Manifest cache
// ---------------------------------------------------------------------------

let manifestPromise: Promise<Record<string, DeviceChromeSpec>> | null = null;
let manifestCache: Record<string, DeviceChromeSpec> | null = null;

async function loadManifest(): Promise<Record<string, DeviceChromeSpec>> {
  if (manifestCache) return manifestCache;

  try {
    const res = await fetch("/device-chrome/manifest.json");
    if (!res.ok) return {};
    manifestCache = await res.json();
    return manifestCache!;
  } catch {
    manifestCache = {};
    return manifestCache;
  }
}

function getManifest(): Promise<Record<string, DeviceChromeSpec>> {
  if (!manifestPromise) {
    manifestPromise = loadManifest();
  }
  return manifestPromise;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Resolve a device_type string to its chrome spec.
 * Returns null if the manifest hasn't loaded yet or the device is unknown.
 */
export function resolveDeviceChrome(
  deviceType: string | null | undefined
): DeviceChromeSpec | null {
  if (!deviceType || !manifestCache) return null;
  return manifestCache[deviceType] ?? null;
}

/**
 * Trigger manifest fetch. Call once on simulator panel mount.
 * After this resolves, `resolveDeviceChrome` returns synchronously.
 */
export async function ensureManifestLoaded(): Promise<void> {
  await getManifest();
}
