/**
 * Device chrome manifest loader — maps device_type strings to frame assets.
 *
 * The manifest is generated by `scripts/prepare-device-chrome.mjs` and placed
 * in `public/device-chrome/manifest.json`. It maps simulator device names
 * (e.g. "iPhone 16 Pro") to their frame asset URL and screen inset percentages.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DeviceChromeSpec {
  /** Chrome family identifier (e.g. "phone11", "tablet5") */
  chromeId: string;
  /** URL to the frame asset (SVG or WebP) in public/ */
  asset: string;
  /** CSS aspect-ratio value for the full device frame (e.g. "436 / 908") */
  aspectRatio: string;
  /** Screen inset percentages — top/bottom are % of height, left/right are % of width */
  screen: {
    top: number;
    left: number;
    right: number;
    bottom: number;
  };
  /** URL to the framebuffer mask SVG (for screen corner clip-path), or null */
  mask: string | null;
}

// ---------------------------------------------------------------------------
// Manifest cache
// ---------------------------------------------------------------------------

let manifestPromise: Promise<Record<string, DeviceChromeSpec>> | null = null;
let manifestCache: Record<string, DeviceChromeSpec> | null = null;
let warnedMissingManifest = false;
const warnedUnsupportedDevices = new Set<string>();

function warnMissingManifest(): void {
  if (!import.meta.env.DEV || warnedMissingManifest) return;
  warnedMissingManifest = true;
  console.warn(
    "[DeviceChrome] device-chrome manifest missing. Run `bun run prepare:device-chrome` on a macOS machine with Xcode installed to enable native simulator bezels. Falling back to the generic device shell."
  );
}

function warnUnsupportedDevice(deviceType: string): void {
  if (!import.meta.env.DEV || warnedUnsupportedDevices.has(deviceType)) return;
  warnedUnsupportedDevices.add(deviceType);
  console.warn(
    `[DeviceChrome] No generated bezel found for "${deviceType}". Falling back to the generic device shell.`
  );
}

async function loadManifest(): Promise<Record<string, DeviceChromeSpec>> {
  if (manifestCache) return manifestCache;

  try {
    const res = await fetch("/device-chrome/manifest.json");
    if (!res.ok) {
      manifestCache = {};
      warnMissingManifest();
      return manifestCache ?? {};
    }
    const parsed = (await res.json()) as Record<string, DeviceChromeSpec> | null;
    manifestCache = parsed ?? {};
    if (Object.keys(manifestCache).length === 0) {
      warnMissingManifest();
    }
    return manifestCache;
  } catch {
    manifestCache = {};
    warnMissingManifest();
    return manifestCache;
  }
}

function getManifest(): Promise<Record<string, DeviceChromeSpec>> {
  if (!manifestPromise) {
    manifestPromise = loadManifest();
  }
  return manifestPromise;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Returns true once the generated manifest has loaded and contains entries. */
export function hasDeviceChromeManifest(): boolean {
  return !!manifestCache && Object.keys(manifestCache).length > 0;
}

/**
 * Resolve a device_type string to its chrome spec.
 * Returns null if the manifest hasn't loaded yet or the device is unknown.
 */
export function resolveDeviceChrome(
  deviceType: string | null | undefined
): DeviceChromeSpec | null {
  if (!deviceType || !manifestCache) return null;
  const spec = manifestCache[deviceType] ?? null;
  if (!spec && hasDeviceChromeManifest()) {
    warnUnsupportedDevice(deviceType);
  }
  return spec;
}

/**
 * Trigger manifest fetch. Call once on simulator panel mount.
 * After this resolves, `resolveDeviceChrome` returns synchronously.
 */
export async function ensureManifestLoaded(): Promise<void> {
  await getManifest();
}
